default: &base
  adapter: mysql2
  username: root
  password: CHANGEMEPLEASE
  host: 127.0.0.1
  encoding: utf8
  variables:
    sql_mode: TRADITIONAL

development:
  database: n2_devel
  <<: *base

misc_logs:
  database: n2_devel_misc_logs
  <<: *base

test:
  database: n2_test
  <<: *base

test_misc_logs:
  database: n2_test_misc_logs
  <<: *base

production:
  database: n2
  <<: *base